### ISSUE TITLE
Bug: Powershell install script always installs channel next

### ISSUE THREAD

**Issue by ntziolis** [che-incubator/chectl#1500]
As today the powershell install script always always downloads installs next channel.

This is true even when explicitly specifying the below before running the script.
```
$CHANNEL = 'stable'
```

The reason for this is that the compute download link function does not take the `$CHANNEL` variable into account and always returns the hardcoded url to the next release.

As you can see from the screenshot below:
![image](https://user-images.githubusercontent.com/265338/127735376-972f602c-4e12-4c99-9b0d-d439037320ef.png)

**Comment by ntziolis** [comment]
After spending almost two weeks getting Che to work, I was negatively impressed with what is provided out of the box. We ended up happily using gitpod.io ever since. especially since it provides a 100% version of vscode and the fact that one can use all extensions without conversion.

**Comment by nickboldt** [comment]
I think this is fixed in a more recent version since we have support now in Dev Spaces for installing from multiple channels using the `dsc` binary (the downstream equivalent of `chectl`). 

If you decide to look at Che or Red Hat OpenShift Dev Spaces again, and see an issue, please report it at https://github.com/eclipse/che/issues.
