### ISSUE TITLE
Improve microk8s support

### ISSUE THREAD

**Issue by l0rd** [che-incubator/chectl#196]
A first PR has been merged to support microk8s but there are some [issues to address](https://github.com/che-incubator/chectl/pull/146#issuecomment-503666001). In particular

- [ ] Use microk8s.kubectl instead of kubectl. Use kubectl if microk8s.kubectl is not found. Fail if none of them is found
- [ ] chectl should not have the responsibility to enable microk8s. we should simply fail if microk8s is not enabled and provide the command line to enable it
- [ ] when enabling the storage addon chectl should wait until it is enabled or timeout if it's not enabled after 60s

**Comment by benoitf** [comment]
Kamino closed and cloned this issue to [eclipse/che](https://github.com/eclipse/che/issues/14455)

**Comment by TheRealChssAddct** [comment]
Starting with the refactor in commit [ b9f6ac7](https://github.com/che-incubator/chectl/commit/b9f6ac7ada95d8b8a99c308f521bb8a96bcec15b), **_chectl server:start  -p microk8s_** began failing for me during k8sTasks.testApiTasks with the following:

```
[13:33:41] Verify Kubernetes API [started]
[13:33:41] Verify Kubernetes API [failed]
[13:33:41] → Failed to connect to Kubernetes API. Error: connect ECONNREFUSED 127.0.0.1:8080
```
I found a couple of workarounds after poking around and seeing the loadFromDefault code in chectl/node_modules/@kubernetes/client-node/dist/config.js.

**Workaround #1**
I found I didn't have a $HOME/.kube/config file.  This is because microk8s doesn't create one. (I don't have kubectl installed, because microk8s.kubectl.) The microk8s readme mentions how to create this file:

> To use MicroK8s with your existing kubectl: 
> sudo microk8s.kubectl config view --raw > $HOME/.kube/config"

however this gives me this error: **"error: write /dev/stdout: permission denied"**

This alternative:
> 'microk8s.config > $HOME/.kube/config' 

gives me this error: **"/snap/microk8s/1079/bin/sed: couldn't flush stdout: Permission denied"**

What I found actually works is this:
> microk8s.config | cat - > $HOME/.kube/config

**Workaround #2**
Guided by this nicja [comment](https://github.com/ubuntu/microk8s/issues/259#issuecomment-494329085) I looked in _/var/snap/microk8s/current/args/kubectl_ to find the pointer to the microk8s kubeconfig file (mine is here: _/var/snap/microk8s/current/credentials/client.config_).

So, theoretically another alternative would be to set the KUBECONFIG environment variable.
Note: I haven't actually tried it, I'm asserting this based on the aforementioned loadFromDefaults code.

**Suggested Fix**
These workarounds shouldn't be necessary.  Perhaps the KubeHelper constructor could be modified to something like this:
```
if (!context) {
   if (flags.platform === 'microk8s') {
      const { stdout } = yield execa('microk8s.config', { timeout: 10000 });
      this.kc.loadFromString(stdout)
```
however, that can introduce an undesireable wait-time in a constructor, so maybe callers should pass in an already retrieved context to new KubeHelper.  
Perhaps the change is as simple as not running the k8sTasks.testApiTasks task when platform = microk8s.
