### ISSUE TITLE
Not able to download chectl older versions.

### ISSUE THREAD

**Issue by gidduhome** [che-incubator/chectl#2027]
Hello Che Team,

I'm trying to download older chectl version (7.41.2). Got Link [7.41.2](https://github.com/che-incubator/chectl/releases/download/7.41.2/chectl-linux-x64.tar.gz ) and did "wget" with that URL. When it was extracted using tar and execute, `chectl version`, it is always displaying as `chectl/7.43.0` though I used 7.41.2 extraction URL link. 

Could someone please clarify is it something intentional to prevent older versions or a bug? Thank you.

**Comment by yujiri8** [comment]
Fascinating! If I download v7.41.2 - or any older version - from within an Ubuntu VM, I get a binary that says it's v7.46.0. But the links work as expected if I download them from my host machine, which is running Artix Linux. It's such a bizarre situation because I verified that the release being downloaded is the same. All I can think of is that the binary has some behavior like "if running on Ubuntu, automatically download and replace self with the v7.46.0 binary" (I know it's not just pretending because it actually has v7.46.0 behavior.

**Comment by nickboldt** [comment]
See solution is linked issue. If you want an older version you can use 

```
export CHECTL_DISABLE_AUTOUPDATE=1
```

but why use an older one?
