### ISSUE TITLE
Allow server:start to deploy a new Che even if one is already running 

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [che-incubator/chectl#32]
It would be nice to have ability set up helm application name. It should resolve conflict in case if user want to have few CHE servers on the one Minikube. For example I used Minikube with already installed CHE. I used `chectl server:start` and I expected that chectl tool will create for me separated new che and I will get two CHE servers. But I've got conflict because, chectl tried to use resources from my first already installed Eclipse CHE in the another namespace, because helm application name was the same.

**Comment by l0rd** [comment]
@AndrienkoAleksandr your scenario makes sense but I would like to avoid the flag to be helm specific because the problem here is more generic: 

> what `server:start` should do if a Che instance is already deployed: update it, create a new one or fail? 

It currently updates it (with `helm update`) but I think a better approach would be to use a flag `--if-already-exist` that accepts 3 values:
- `fail` (the default)
- `update`
- `new-instance`

What do you think?

**Comment by AndrienkoAleksandr** [comment]
Looks good for me.
