### ISSUE TITLE
Provide a script for the installation that detect the OS and proceed installation

### ISSUE THREAD

**Issue by slemeur** [che-incubator/chectl#36]
We could provide a script which would simplify the installation of chectl.

Like the one from HELM:
https://raw.githubusercontent.com/helm/helm/master/scripts/get

Like the one from ODO:
https://github.com/redhat-developer/odo/blob/master/scripts/install.sh

**Comment by l0rd** [comment]
I like the idea of the script. It has some security issues but it's pretty effective.

Otherwise oclif natively provides a few options to generate real installers for different OSes: https://oclif.io/docs/releasing

That has many benefits as the autoupdate feature and a more reliable way to package nodejs (today we are using https://github.com/zeit/pkg that requires some hacks to work properly).

The drawback is that an installer may be considered to invasive.

Anyway that's how heroku distributes its CLI.

If you think an installer would be fine let's go the installer way. That's pretty straightforward. Otherwise let's do the script. That should be easy as well.
