### ISSUE TITLE
Cache directory gets corrupted.

### ISSUE THREAD

**Issue by tsmaeder** [che-incubator/chectl#61]
Following our che-in-che guide, I could not start che with the following error:
```
  ✖ Deploy Che Server
    → Update Complete. ⎈Happy Helming!⎈
    Waiting for Che Server to start and respond
    Retrieving Che Server URL
Error: Command failed: /bin/sh -c helm dependencies update /home/thomas/.cache/chectl/templates/kubernetes/helm/che/
Error: Unable to move current charts to tmp dir: rename /home/thomas/.cache/chectl/templates/kubernetes/helm/che/charts /home/thomas/.cache/chectl/templates/kubernetes/helm/che/tmpcharts: file exists
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
    Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
    at makeError (/snapshot/chectl/node_modules/execa/index.js:174:9)
    at module.exports.Promise.all.then.arr (/snapshot/chectl/node_modules/execa/index.js:278:16)
```

After removing the directory ~/.cache/chectl, everything worked fine.

ideally, the cache would not need to be cleaned, but should have "chectl cleanup" or "chectl purge" to clean any state that might be corrupted.

**Comment by l0rd** [comment]
From the output it looks like the command fails initially but is then completed successfully. Hence I would say it's a timeout issue rather than a cache corruption: `execa` doesn't wait for the (successful) completion of the command and returns an error.

From the output logs I figured out that you used an old version of chectl (before #45). At the time the timeout was 10s but has been increased to 2 min now with #54. 

I am closing the issue because it has already been fixed but feel free to re-open otherwise.

**Comment by tsmaeder** [comment]
It's strange that a cache would actually make stuff slower. Also, there is no indication that this is a timeout from the output (at least not if you don't know the source code). Maybe improve the logging?
