### ISSUE TITLE
Notify user when there is a new version of chectl or allow to update

### ISSUE THREAD

**Issue by benoitf** [che-incubator/chectl#72]
- https://oclif.io/docs/releasing.html#autoupdater
- https://github.com/oclif/plugin-update
- https://www.npmjs.com/package/@oclif/plugin-warn-if-update-available

**Comment by nickboldt** [comment]
Having discussed the options and requirements with @l0rd, here's the plan:

[ ] take travis script, port to jenkinsfile
[ ] set up job in crw jenkins to run jenkinsfile on any git commit events
[ ] switch build from pkg to npx oclif-dev pack
[ ] push resulting tarball via rsync over ssh to https://dl.jb.o/jbosstools/che-incubator/chectl/dist/chectl.tar.gz

**Comment by benoitf** [comment]
I'm not sure why pkg shouldn't be used ? As it's offering single binary without pre-requesites and how it is related to changing CI as well

**Comment by l0rd** [comment]
@nickboldt wants to help us setting up a Jenkins job that would publish the artifacts to download.jboss.org. 

He needed more details to setup the Jenkins build and I've pointed him to the travis.yml and told him that we need to move from `pkg` to `oclif-dev pack` to be able to use the `autoupdate` feature. At least that's what I understand from docs [here](https://oclif.io/docs/releasing#autoupdater) and [here](https://oclif.io/docs/faqs#i-want-a-single-binary-cli-like-with-go).

And [I wanted to give a try to the tarball packaging](https://github.com/che-incubator/chectl/issues/36#issuecomment-457013341) in any case because:
- `pkg` has a couple of annoying issues
- oclif documentation suggest not to use pkg

**Comment by l0rd** [comment]
@nickboldt I have run ` npx oclif-dev pack` locally and the result is:

```
./dist/
|-- chectl-v0.0.2
    |-- chectl-v0.0.2-darwin-x64.tar.gz
    |-- chectl-v0.0.2-linux-arm.tar.gz
    |-- chectl-v0.0.2-linux-x64.tar.gz
    |-- chectl-v0.0.2-win32-x64.tar.gz
    |-- chectl-v0.0.2-win32-x86.tar.gz
    `-- chectl-v0.0.2.tar.gz
 ```

so the format of the URLs will be `https://dl.jb.o/jbosstools/che-incubator/chectl/dist/chectl-vX.Y.Z/chectl-vX.Y.Z-<os>-<arch>.tar.gz`

**Comment by nickboldt** [comment]
There are other `s3.templates` you can use -- not sure how, but there are options:

https://github.com/oclif/config/blob/master/src/config.ts#L207-L223

Looks like you're using the default `versioned` approach:

https://github.com/oclif/config/blob/master/src/config.ts#L212

I suspect we want to exclude x86 and arm - right?

**Comment by l0rd** [comment]
We can exclude `x86` and `arm` (not sure what's the benefit). And we I think we need to do some changes to our CLI (at least adding the plugin-update and setting the configuration to point to `https://dl.jb.o/jbosstools/che-incubator/chectl/dist/`). That's something @benoitf can work on once we have setup the folder at `dl.jb.o`.

And coming back to the folder structure I like the Heroku approach described [here](https://oclif.io/docs/releasing#autoupdate-channels): we should use a `vX.Y.Z-beta` versions that would be overwritten at every commit and users could install subscribing to the beta channel (`chectl update beta`) and once every 3 weeks release a new `vX.Y.Z` version for users subscribed to the stable channel.

**Comment by nickboldt** [comment]
Making progress ...

https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Builds/job/eclipse-chectl_master/10/console
--> http://download.jboss.org/jbosstools/che-incubator/chectl/dist/

But I can't build the windows tarballs as the CRW Jenkins nodes dont have 7zip installed. Any idea how to either skip building for Windows, or use a different tar compression util, like xz or gzip?

**Comment by l0rd** [comment]
@nickboldt I have installed p7zip on my mac and it work fine.

**Comment by l0rd** [comment]
If you still can't install a `7zip` tool you can `npx oclif-dev pack -t "linux-x64,darwin-x6a"`

**Comment by nickboldt** [comment]
OK, I've got linux arm, linux 64 and darwin here:

http://download.jboss.org/jbosstools/che-incubator/chectl/dist/chectl-v0.0.2-66ce/

Job is here:

https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Builds/job/eclipse-chectl_master/

Once merged, I can update the job to pull from origin/master instead of [my fork's pull request](https://github.com/che-incubator/chectl/pull/79)

I'm still not sure how to use oclif-dev to build windows binary when 7zip is not installed, but I opened this:

https://github.com/oclif/dev-cli/issues/96

**Comment by nickboldt** [comment]
"I have installed p7zip on my mac and it worked fine." Your mac is not my Jenkins openstack node. "It works on my machine" is not how we roll CI builds. :P

**Comment by nickboldt** [comment]
Haven't moved forward w/ the 7zip fix as we need to first verify that the oclif autoupdate thing even works. Back to you in the studio, Florent.

**Comment by benoitf** [comment]
ok

**Comment by nickboldt** [comment]
So my PR in #79 is merged. Has anyone had time to check if the content published on dl.jb.o works for you? Asking because my job https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Builds/job/eclipse-chectl_master/ is now failing due to host key verification failure, which I can fix but won't bother if you're still not using the output of the build. :D 

Let me know how to proceed here! @l0rd @benoitf

**Comment by benoitf** [comment]
I should be able to test with existing two revs at dl.jboss.org http://download.jboss.org/jbosstools/che-incubator/chectl/dist/

(I'm on PTO next week)

**Comment by benoitf** [comment]
@nickboldt 

so basically the content inside `dist/` folder can be used but there are still missing pieces for the self-update mechanism

It requires a manifest file
Debugging what is read from the update plug-in, I ended with the following files that are required

- At the root of the dist folder a manifest file is used
name is for example for macOS: `darwin-x64`

```
$ ls
darwin-x64  dist
```

and the content I used is
```
$ cat darwin-x64 
{
"version" : "0.0.2-66ce",
"channel": "stable",
"gz" : "http://www-full-url-tochectl-download-website/che-incubator/chectl/dist/chectl-v0.0.2-66ce/chectl-v0.0.2-66ce-darwin-x64.tar.gz"
}
```

so @nickboldt AFAIK we would need these files per arch:
`linux-x64`, `linux-arm`

It should contain the latest version in its version attribute and in gz attribute, the absolute full path to the archive binary.

**Comment by benoitf** [comment]
![update-chectl](https://user-images.githubusercontent.com/436777/58031654-1d773680-7b21-11e9-8235-b5474813e1b2.gif)

(at the end there is an update command failed as the current uploaded binaries don't have the update command)

**Comment by benoitf** [comment]
@nickboldt do you have some ETA when you'll be able to provide this new layout ?

**Comment by nickboldt** [comment]
Apologies -- been a bit busy with CRW. Just nag me frequently to make things move faster :) 

Meanwhile I've added what I think should generate the metadata but... the job keeps failing (npm is crashing):

https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Builds/job/eclipse-chectl_master/29/console

I've tried several things but everything just fails:

https://github.com/nickboldt/chectl/commits/issue-72

**Comment by nickboldt** [comment]
Thanks to Mario's help I'm past the blockage (unable to build). Will look at why my shell script is failing tomorrow. Might have to break down and use groovy instead of shell :)

https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Builds/job/eclipse-chectl_master/39/console

**Comment by nickboldt** [comment]
PR to add json manifests: https://github.com/che-incubator/chectl/pull/139/files
